name: CI

env:
  NODE_VERSION: 22
  ARTIFACT_NAME: build
  BUILD_DIR: build/client

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - ".agents/**"
jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      node-version: ${{ env.NODE_VERSION }}
      artifact-name: ${{ env.ARTIFACT_NAME }}
